name: Renovate CI
on:
  pull_request:
  workflow_dispatch:

jobs:
  get-changed-file:
    if: contains(github.head_ref, 'renovate/')
    runs-on: ubuntu-latest
    outputs:
      name: ${{ steps.changed-file.outputs.all_changed_files }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: Get changed files
        uses: tj-actions/changed-files@v45
        id: changed-files

      - name: Get first changed file
        id: changed-file
        run: echo "name=$(echo ${{ steps.changed-files.outputs.all_changed_files }} | head -n 1)" >> $GITHUB_OUTPUT

      - name: Debug
        run: echo ${{ contains(steps.changed-file.outputs.name, 'docker-compose.json') }}

  update-config:
    needs: get-changed-file
    runs-on: ubuntu-latest
    if: contains(needs.get-changed-file.outputs.name, 'docker-compose.json')
    outputs:
      auto_merge: ${{ steps.update.outputs.auto_merge }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Run script
        id: update
        run: echo "auto_merge=$(bun .github/scripts/update.ts ${{ needs.get-changed-file.outputs.name }})" >> $GITHUB_OUTPUT

      - name: Commit
        uses: EndBug/add-and-commit@v9
        with:
          message: "chore: update config"

  auto_merge_label:
    needs: update-config
    runs-on: ubuntu-latest
    if: ${{ needs.update-config.outputs.auto_merge == '{"auto_merge":true}' }}
    steps:
      - name: Add automerge label if auto_merge is true
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.rest.issues.addLabels({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ["automerge"]
            })
