name: Renovate
on:
  workflow_dispatch:

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup node
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install renovate
        run: npm install -g renovate

      - name: Run renovate
        run: renovate --token ${{ secrets.RENOVATE_TOKEN }} ${{ github.repository.owner }}/${{ github.repository.repo }}
