name: Renovate
on:
  workflow_dispatch:
  issues:

jobs:
  renovate:
    runs-on: ubuntu-latest
    if: ${{ (github.event_name == 'workflow_dispatch') || (github.event.issue.number == 17) }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: "22"

      - name: Setup bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install renovate
        run: npm install -g renovate

      - name: Echo repository
        run: echo ${{ github.repository }}

      - name: Run renovate
        run: renovate --token ${{ secrets.GITHUB_TOKEN }} ${{ github.repository }}
